version: '3'
services:
  app-server:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    networks:
      - onlyoffice
    volumes:
      - app_data:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx-server:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    command: ["nginx", "-c", "/data/conf/nginx.conf", "-g", "daemon off;"]
    ports:
      - 80:80
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - nginx_data:/data
      - app_data:/var/www/html
networks:
  onlyoffice:
    driver: overlay
volumes:
  document_data:
    external: true
  document_log:
    external: true
  app_data:
    external: true
  nginx_data:
    external: true

# docker volume rm nginx_data
# docker volume create nginx_data
# docker run -v nginx_data:/data --name helper busybox true
# docker cp ./nginx/conf helper:/data
# docker rm helper

# docker volume rm app_data
# docker volume create app_data
# docker run -v app_data:/var/www/html/ --name helper busybox mkdir /var/www/html/apps
# docker cp ./onlyoffice helper:/var/www/html/apps/
# docker rm helper
